PPM_Project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', RedirectView.as_view(pattern_name='events:index')),
    path('events/', include('events.urls')),
    path('admin/', admin.site.urls),
    path('reset-password', auth_views.PasswordResetView.as_view(template_name='events/password_reset.html'), name='reset_password'),
    path('reset-password/done', auth_views.PasswordResetDoneView.as_view(template_name='events/password_reset_sent.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='events/password_reset_form.html'), name='password_reset_confirm'),
    path('reset-password/complete', auth_views.PasswordResetCompleteView.as_view(template_name='events/password_reset_done.html'), name='password_reset_complete')
]

events/urls.py
from django.urls import path

from . import views

app_name = 'events'
urlpatterns = [
    path('', views.index, name='index'),
    path('add/', views.add, name='add'),
    path('events/login/', views.login_page, name='login_page'),
    path('login/', views.login_page, name='login_page'),
    path('logout/', views.logout_user, name='logout_user'),
    path('add/done/', views.add_done, name='add_done'),
    path('<year>-<month>-<day>/', views.day_events, name='day_events'),
    path('<year>-<month>-<day>/<event_id>/', views.event_details, name='event_details'),
    path('<year>-<month>-<day>/<event_id>/edit', views.event_edit, name='event_edit'),
    path('<year>-<month>-<day>/<event_id>/edit/done', views.event_edit_done, name='event_edit_done'),
    path('<year>-<month>-<day>/<event_id>/remove', views.event_remove, name='event_remove'),
    path('<year>-<month>-<day>/<event_id>/remove/done', views.event_remove_done, name='event_remove_done'),
    path('add-user/', views.add_user, name='add_user'),
    path('review/<event_id>', views.review_events, name='review_events'),
    path('review/done/<event_id>', views.review_done, name='review_done'),
]

events/models.py
import datetime
from django.contrib.auth.models import User
from django.db import models
from django.utils import timezone

# Create your models here.
class Event(models.Model):
    event_name = models.CharField(max_length=200)
    event_date = models.DateField('Event date')
    start_time = models.TimeField()
    end_time = models.TimeField()
    event_desc = models.CharField(max_length=400)
    event_reviewed = models.BooleanField(default = False)
    event_location = models.CharField(default = "",max_length=200)
    event_user = models.ForeignKey(User, default=None, on_delete = models.CASCADE)
    def __str__(self):
        return self.event_name

class Review(models.Model):
    event_reviewed = models.ForeignKey(Event, default = None, on_delete = models.CASCADE)
    review = models.CharField(max_length=400)
    attended = models.BooleanField(default = True)
    attendance = models.IntegerField()
    rating = models.IntegerField()

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete = models.CASCADE)
    hex_code = models.CharField(max_length=6, default = '#ADD8E6')


    def __str__(self):
        return self.user.first_name + ' ' + self.user.last_name

events/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class DateInput(forms.DateInput):
    input_type = 'date'

class DateForm(forms.Form):
    event_name = forms.CharField(label='Event_name', max_length=100)
    event_date = forms.DateField(widget = DateInput)

class CreateUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2', 'first_name', 'last_name']

        #def clean_email(self):
            #email = self.cleaned_data.get('email')
            #if not email.endswith('police.uk'):
                #raise forms.ValidationError("Only .police.uk email addresses allowed")
            #return email

events/views.py
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.shortcuts import render, redirect
from django.utils import timezone
from django.contrib import messages
import calendar, datetime, random
from django.db.models import F
from django.core.mail import send_mail

from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required


from .decorators import admin_only, check_if_logged_in, admin_or_creator_only, admin_or_creator_only_review

from .models import Event, UserProfile, Review
from .forms import DateForm, CreateUserForm

# Create your views here.
@login_required(login_url='events:login_page')
def index(request):
    if 'monthCount' in request.session:
        monthCount = request.session['monthCount']
    else:
        monthCount = 0
        request.session['monthCount'] = monthCount

    if 'yearCount' in request.session:
        yearCount = request.session['yearCount']
    else:
        yearCount = 0
        request.session['yearCount'] = yearCount

    if request.method == 'POST':
        if request.POST.get('next'):
            monthCount += 1
            request.session['monthCount'] = request.session['monthCount'] + 1
        elif request.POST.get('prev'):
            monthCount -= 1
            request.session['monthCount'] = request.session['monthCount'] - 1
        else:
            monthCount = 0
            yearCount = 0
            request.session['monthCount'] = 0
            request.session['yearCount'] = 0
    if timezone.now().month+monthCount == 13 :
        monthCount = - timezone.now().month+1
        yearCount = yearCount + 1
    if timezone.now().month+monthCount == 0 :
        monthCount = 12 - timezone.now().month
        yearCount = yearCount - 1
    c = calendar.Calendar(calendar.MONDAY)
    c_list = c.monthdayscalendar(timezone.now().year+yearCount, timezone.now().month+monthCount)
    temp_w_iter = 0
    for week in c_list:
        temp_d_iter = 0
        for day in week:
            event_list = []
            event_set = Event.objects.filter(event_date__year=timezone.now().year+yearCount, event_date__month=timezone.now().month+monthCount, event_date__day=day)
            for event in event_set:
                user = event.event_user
                user_details = User.objects.get(username = user)
                event_list.append([event,event.pk,user_details])
            if len(event_list) != 0:
                c_list[temp_w_iter][temp_d_iter] = [day,event_list]
            else: c_list[temp_w_iter][temp_d_iter] = [day]
            temp_d_iter += 1
        temp_w_iter += 1
    del temp_d_iter, temp_w_iter
    today = timezone.now().day
    current_month = timezone.now().month
    event_review_set = Event.objects.filter(event_date__range=["2011-01-01", timezone.now()], event_user = request.user, event_reviewed = False)
    event_reviews = []
    for event in event_review_set :
        event_reviews.append(event)
        print(event)

    event_review_set = Event.objects.filter(event_date__range=["2011-01-01", timezone.now()], event_user=request.user,
                                            event_reviewed=False)
    event_reviews = []
    for event in event_review_set:
        event_reviews.append(event)
        print(event)

    is_admin = 0
    if request.user.is_superuser:
        is_admin = 1

    context = {'c_list': c_list, 'year': timezone.now().year+yearCount, 'month': timezone.now().month+monthCount, 'today': today, 'current_month':current_month, 'is_admin': is_admin, 'event_review':event_reviews}
    return render(request, 'events/index.html', context)

@login_required(login_url='events:login_page')
def add(request):
    is_admin = 0
    if request.user.is_superuser:
        is_admin = 1

    users = UserProfile.objects.all()

    context = {'form': DateForm(), 'is_admin': is_admin, 'users': users}
    return render(request, 'events/add.html', context)

@login_required(login_url='events:login_page')
def add_done(request):
    if request.user.is_superuser:
        user = User.objects.get(pk=request.POST.get('users'))
    else:
        user = request.user
    event = Event(event_name=request.POST['name'],event_date=request.POST['date'],event_desc=request.POST['description'],start_time=request.POST['start_time'],end_time=request.POST['end_time'], event_location=request.POST['event_location'], event_user = user)
    event.save()

    email_message = "You have been assigned to an event: " + event.event_name + "\nDate: " + event.event_date + "\n" + event.start_time + "-" + event.end_time 

    account_email = user.email

    send_mail('Event Assigned', email_message , account_email, [account_email], fail_silently = False)

    return HttpResponseRedirect(reverse('events:index'))

@login_required(login_url='events:login_page')
def day_events(request, year, month, day):
    time_events = []
    time = datetime.time(8, 0, 0)
    count_mins = 0
    count = 0
    print(time)
    while time < datetime.time(23, 0, 0):
        event_list = []
        event_set = Event.objects.filter(event_date__year=year,
                                         event_date__month=month, event_date__day=day,
                                         start_time=time)
        for event in event_set:
            user = event.event_user
            user_colour = User.objects.get(username = user)
            temptime = time
            time_slots = (event.end_time.hour - event.start_time.hour) * 2
            event_list.append([event, time_slots, user_colour])
        time_events.append([time, event_list])
        count_mins = count_mins + 30
        if count_mins == 60:
            count = count + 1
            count_mins = 0
        time = datetime.time(8+count, 0 + count_mins, 0)

    event = 0
    context = {'year': year, 'month': month, 'day': day, 'time_events': time_events}
    return render(request, 'events/day_event_layout.html', context)

@admin_only
@login_required(login_url='events:login_page')
def add_user(request):
    form = CreateUserForm()

    if request.method == 'POST':
        form = CreateUserForm(request.POST)
        if form.is_valid():
            user_saved = form.save()

            r = lambda: random.randint(0,255)
            code = ('#%02X%02X%02X' % (r(),r(),r()))

            user_profile = UserProfile(user = user_saved, hex_code = code)

            user_profile.save()

            messages.success(request, "Account created successfully!")

            email_message = 'Account successfully Created:' + user_saved.username

            account_email = user_saved.email

            send_mail('Account  Created', email_message, account_email, [account_email] ,fail_silently = False)

            return redirect('events:index')

    is_admin = 0
    if request.user.is_superuser:
        is_admin = 1

    context = {'form': form, 'is_admin': is_admin}
    return render(request, 'events/create_account.html', context)

@check_if_logged_in
def login_page(request):
    if request.method == 'POST':
        username = request.POST.get('user')
        password = request.POST.get('pwd')
        
        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            today = datetime.date.today()
            week_ago = today - datetime.timedelta(days=7)
            email_message = 'Events Require Reviewing: '
            eventset = Event.objects.filter(event_user_id = user.id, event_reviewed = False, event_date__range=["2011-01-01", week_ago] )
            if eventset.count() != 0:
                for event in eventset:
                     email_message = email_message+ event.event_name + "\n"
                email_message = email_message + "These events are over a week old, please review them."
                account_email = user.email
                send_mail('Event Requires Reviewing', email_message, account_email, [account_email] ,fail_silently = False)
            return redirect('events:index')
        else:
            messages.info(request, 'Username or Password incorrect!')

    context = {}
    return render(request,'events/login.html', context)

@login_required(login_url='events:login_page')
def logout_user(request):
    logout(request)
    return redirect('events:login_page')

@login_required(login_url='events:login_page')
def event_details(request, year, month, day, event_id):
    event = Event.objects.get(pk=event_id)
    user = event.event_user
    review = None
    user_details = User.objects.get(username = user)
    if (event.event_reviewed == True):
        review = Review.objects.get(event_reviewed = event_id)
    can_change = 0
    if request.user.id == event.event_user.id or request.user.is_superuser:
        can_change = 1

    context = {'date':event.event_date, 'event':event, 'start':event.start_time, 'end':event.end_time, 'description':event.event_desc, 'user':user_details, 'can_change': can_change, 'year': year, 'month':month, 'day':day,'location':event.event_location, 'event_id':event_id,'review':review}
    return render(request, 'events/event_details.html',context)

@admin_or_creator_only
@login_required(login_url='events:login_page')
def event_edit(request, year, month, day, event_id):
    event = Event.objects.get(pk=event_id)

    is_admin = 0
    if request.user.is_superuser:
        is_admin = 1

    users = UserProfile.objects.all()

    start_time_hour = "%02d" % event.start_time.hour
    start_time_min = "%02d" % event.start_time.minute
    end_time_hour = "%02d" % event.end_time.hour
    end_time_min = "%02d" % event.end_time.minute

    context = {'year': year, 'month':month, 'day':day, 'event_id':event_id, 'event': event, 'is_admin': is_admin, 'users': users, 'start_time_hour':start_time_hour, 'end_time_hour': end_time_hour, 'start_time_min':start_time_min, 'end_time_min': end_time_min}

events/templates/events/add.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Add event</title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <style>
        td:hover{
            background-color: lavender;
        }

	th {
	    background-color: #f2f2f2;
	    width: 120px;

	}



	tr:nth-child(even) {background-color: #f2f2f2;}

    .sidenav {
      height: 100%;
      width: 0;
      position: fixed;
      z-index: 1;
      top: 0;
      left: 0;
      background-color: #111;
      overflow-x: hidden;
      transition: 0.5s;
      padding-top: 60px;
    }

   #inner_table {
      border-collapse: separate;
      border-spacing: 5px;
    }

    .sidenav a {
      padding: 8px 8px 8px 32px;
      text-decoration: none;
      font-size: 25px;
      color: #818181;
      display: block;
      transition: 0.3s;
    }

    .sidenav a:hover {
      color: #f1f1f1;
    }

    .sidenav .closebtn {
      position: absolute;
      top: 0;
      right: 25px;
      font-size: 36px;
      margin-left: 50px;
    }

    @media screen and (max-height: 450px) {
      .sidenav {padding-top: 15px;}
      .sidenav a {font-size: 18px;}
    }
	
	h1 {
	    color : #E8E8E8;
	    border: 2px solid #3498DB;
 	    padding: 0.5rem;
	    padding-bottom: 0.5rem;
	    width = 100%;
	    
	    background: #3498DB;
	    font-weight:normal;
	}

	body {
	     background: #E8E8E8;
	     font-family:sans-serif;
	}
	form {
	     background: white;
	     margin:3rem auto;
	     max-width:500px;
	     border: 2px solid #3498DB;
	     padding: 2rem;
	     border-radius: 5px;
		
    }
	input {
	     display:block;
	     width: 100%	
	}
	
	#btn {
	     border:0;
	     height: 2rem;
	     background:#3498DB;
	     text-transform:uppercase;
	     cursor:pointer;
	     width:auto;
	      &:hover{
		background:#3498D8;
		}   
	}


    </style>
</head>
<body>
<div id="mySidenav" class="sidenav">
    <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
    <a href="{% url 'events:index' %}">Events</a>
    {% if is_admin %}
    <a href="{% url 'events:add_user' %}">Add User</a>
    <a href="{% url 'admin:index' %}">Database</a>
    {% endif %}
    <a href="{% url 'events:logout_user' %}">Log out</a>
</div>
<span style="font-size:30px;cursor:pointer" onclick="openNav()">&#9776; Menu</span>

<script>
function openNav() {
  document.getElementById("mySidenav").style.width = "250px";
}

function closeNav() {
  document.getElementById("mySidenav").style.width = "0";
}
</script>

<form action="{% url 'events:add_done'%}" method="post">
    <h1 style="text-align:center">Add Event To Calendar</h1>
    {% csrf_token %}
    <label for="name">Event name: </label>
    <input type="text" name="name" id="name" required><br>
    {% if is_admin == 1 %}
        <label for="users">Event coordinator: </label>
        <select id="users" name="users">
            {% for user in users %}
                <option value="{{ user.user.id }}">{{ user }}</option>
            {% endfor %}
        </select><br><br>
    {% endif %}
    <label for="date">Event date: </label>
    <input type="date" name="date" id="date" required><br>
    <label for="start_time">Event Start Time: </label>
    <input type="time" step="1800" min="08:00" max="22:30" name ="start_time" id="start_time" required><br>
    <label for="end_time">Event End Time: </label>
    <input type="time" step="1800" min="08:00" max="22:30" name ="end_time" id="end_time" required><br>
    <label for="location">Event Postcde: </label>
    <input type="text" name ="event_location" id="event_location"><br>
    <label for="description">Event Description: </label>
    <textarea id="description" name="description" rows="10" cols="69"></textarea>
<input type="submit" value="Add event" id = "btn">
</form>
</body>
</html>

events/templates/events/create_account.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <style>
        td:hover{
            background-color: lavender;
        }

	th {
	    background-color: #f2f2f2;
	    width: 120px;

	}



	tr:nth-child(even) {background-color: #f2f2f2;}

    .sidenav {
      height: 100%;
      width: 0;
      position: fixed;
      z-index: 1;
      top: 0;
      left: 0;
      background-color: #111;
      overflow-x: hidden;
      transition: 0.5s;
      padding-top: 60px;
    }

   #inner_table {
      border-collapse: separate;
      border-spacing: 5px;
    }

    .sidenav a {
      padding: 8px 8px 8px 32px;
      text-decoration: none;
      font-size: 25px;
      color: #818181;
      display: block;
      transition: 0.3s;
    }

    .sidenav a:hover {
      color: #f1f1f1;
    }

    .sidenav .closebtn {
      position: absolute;
      top: 0;
      right: 25px;
      font-size: 36px;
      margin-left: 50px;
    }

    @media screen and (max-height: 450px) {
      .sidenav {padding-top: 15px;}
      .sidenav a {font-size: 18px;}
    }
    	h1 {
	    color : #E8E8E8;
	    border: 2px solid #3498DB;
 	    padding: 0.5rem;
	    padding-bottom: 0.5rem;
	    width = 100%;

	    background: #3498DB;
	    font-weight:normal;
	}

	body {
	     background: #E8E8E8;
	     font-family:sans-serif;
	}
	form {
	     background: white;
	     margin:3rem auto;
	     max-width:500px;
	     border: 2px solid #3498DB;
	     padding: 2rem;
	     border-radius: 5px;

    }
	input {
	     display:block;
	     width: 100%
	}

	#btn {
	     border:0;
	     height: 2rem;
	     background:#3498DB;
	     text-transform:uppercase;
	     cursor:pointer;
	     width:auto;
	      &:hover{
		background:#3498D8;
		}
	}


    </style>
    <title>Add a user</title>
</head>
<body>
<div id="mySidenav" class="sidenav">
    <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
    <a href="{% url 'events:index' %}">Events</a>
    <a href="{% url 'events:add' %}">Add</a>
    {% if is_admin %}
    <a href="{% url 'admin:index' %}">Database</a>
    {% endif %}
    <a href="{% url 'events:logout_user' %}">Log out</a>
</div>
<span style="font-size:30px;cursor:pointer" onclick="openNav()">&#9776; Menu</span>

<script>
function openNav() {
  document.getElementById("mySidenav").style.width = "250px";
}

function closeNav() {
  document.getElementById("mySidenav").style.width = "0";
}
</script>
<form action="" method="post">
    <h1 style="text-align:center">Add A New User</h1>
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" name="create_user" id = "btn">
</form>
</body>
</html>

events/templates/events/event_details.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <meta charset="UTF-8">
    <title>{{ event.event_name }} on {{ event.event_date }}</title>
    <style>
	
	h1 {
	    color : #E8E8E8;
 	    padding: 0.5rem;
	    padding-bottom: 0.5rem;
	    width = 100%;    
	    background: #787878;
	    font-weight:normal;
	}
	
	h2 {
		color : #424242;
		padding: 0.5rem;
	    padding-bottom: 0.5rem;
		width = 100%;
	}
	
	h3{
		color : #5e5e5e;
		padding: 0.5rem;
	}
	
	p{
		color : #303030;
		padding: 0.5rem;
	}
	
	body {
	     background: #E8E8E8;
	     font-family:sans-serif;
	}
	
	p {
		padding: 0.7rm;
	}

    </style>
</head>
<body>
<script>
    setTimeout(function(){
   window.location.reload(1);
}, 5000);
</script>

    <h1 style="text-align:left">Event Details</h1>
    <h2>{{ event.event_name }}</h2>
	<h3>{{ event.event_date }}</h3>
	<h3>{{ event.start_time }} - {{ event.end_time }}</h3>
	<p>{{ event.event_desc }}</p>
	<p>{{ event.event_location }}</p>
	<p>Assigned To: {{user.first_name}} {{user.last_name}}</p>
    {% if review %}
	<p>Attended: {{ review.attended }}</p>
	<p>Attendance: {{ review.attendance }}</p>
	<p>Rating: {{ review.rating }}</p>
	<p>Review: {{ review.review }}</p>
    {% endif %}
    {% if can_change %}
        <hr>
        <form action="{% url 'events:event_edit' year month day event_id%}">
            <input type="submit" value="Edit" />
        </form>
        <form action="{% url 'events:event_remove' year month day event_id%}">
            <input type="submit" value="Remove" />
        </form>
    {% endif %}
</body>
</html>

events/templates/events/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <style>
        td:hover{
            background-color: lavender;
        }
	
	th {
	    background-color: #ADD8E6;
	    width: 120px;
	    
	}	
	

	
	tr:nth-child(even) {background-color: #f2f2f2;}

    .sidenav {
      height: 100%;
      width: 0;
      position: fixed;
      z-index: 1;
      top: 0;
      left: 0;
      background-color: #111;
      overflow-x: hidden;
      transition: 0.5s;
      padding-top: 60px;
    }

   #inner_table {
      border-collapse: separate;
      border-spacing: 5px;
    }

    .sidenav a {
      padding: 8px 8px 8px 32px;
      text-decoration: none;
      font-size: 25px;
      color: #818181;
      display: block;
      transition: 0.3s;
    }

    .sidenav a:hover {
      color: #f1f1f1;
    }

    .sidenav .closebtn {
      position: absolute;
      top: 0;
      right: 25px;
      font-size: 36px;
      margin-left: 50px;
    }

    @media screen and (max-height: 450px) {
      .sidenav {padding-top: 15px;}
      .sidenav a {font-size: 18px;}
    }
    </style>
    <title>Calendar</title>
</head>
<body {%if event_review %}
        {% for event in event_review %}
		target="popup" onload="window.open('review/{{ event.id}}', '_blank');"
	{% endfor %}
      {% endif %}
>




<div id="mySidenav" class="sidenav">
    <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
    <a href="{% url 'events:add' %}">Add</a>
    {% if is_admin %}
    <a href="{% url 'events:add_user' %}">Add User</a>
    <a href="{% url 'admin:index' %}">Database</a>
    {% endif %}
    <a href="{% url 'events:logout_user' %}">Log out</a>
</div>
<span style="font-size:30px;cursor:pointer" onclick="openNav()">&#9776; Menu</span>

<script>
function openNav() {
  document.getElementById("mySidenav").style.width = "250px";
}

function closeNav() {
  document.getElementById("mySidenav").style.width = "0";
}
</script>

<div id="cal" class="container" >
    {% for message in messages %}
        <p>{{ message }}</p>
    {% endfor %}

    <h2>{{ month }}/{{ year }}</h2>


    <table class="table table-bordered">
        <thead>
        <tr>
            <th>Monday</th>
            <th>Tuesday</th>
            <th>Wednesday</th>
            <th>Thursday</th>
            <th>Friday</th>
            <th>Saturday</th>
            <th>Sunday</th>
        </tr>
        </thead>
        <tbody>

	
            {% for week in c_list %}
                <tr>
                {% for day in week %}
                    {% if day.0 != 0 %}
                        {% if today == day.0 %}
                            <td> <a target="popup" onclick="window.open('{{ year }}-{{ month }}-{{ day.0 }}','name','width=600,height=400')" style="background-color: lightblue">{{ day.0 }}</a></td>
                            {% if current_month == month %}
                                <td  style="background-color: lightcyan"> <a target="popup" onclick="window.open('{{ year }}-{{ month }}-{{ day.0 }}','name','width=600,height=400')">{{ day.0 }}</a></td>
                            {% else %}
                                <td> <a target="popup" onclick="window.open('{{ year }}-{{ month }}-{{ day.0 }}','name','width=600,height=400')">{{ day.0 }}</a></td>
                            {% endif %}
                        {% else %}		   
                            <td style="height: 150px";>
			    <table id="inner_table">  
                      	    <tr id = "event_item"><td style="cursor:pointer;"><a target="popup" onclick="window.open('{{ year }}-{{ month }}-{{ day.0 }}','name','width=600,height=400')">{{ day.0 }}</a></td></tr>
			    {% for event in day.1 %} 
                    <tr><td style="background-color: {{event.2.userprofile.hex_code}}; border-radius: 5px; padding-right: 10px; padding-left: 5px; cursor:pointer; colour: white;"><a  style = "color: white;" target="popup" onclick="window.open('{{ year }}-{{ month }}-{{ day.0 }}/{{ event.1 }}','test','width=600,height=400')">{{ event.0 }}</a></td></tr>
			    {% endfor %}
    			    </table>
			    </td>
                        {% endif %}
                    {% else %}
                        <td style="background: #d3d3d3"></td>
                    {% endif %}
                {% endfor %}
                </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

<form action="" method="post">
    {% csrf_token %}
    <input type="submit"  style="padding: 5px 10px; margin-left:200px;" value="Next" name="next"/>
</form>
<form action="" method="post">
    {% csrf_token %}
    <input type="submit"  style="padding: 5px 10px; margin-left:200px;" value="Previous" name="prev"/>
</form>
<form action="" method="post">
    {% csrf_token %}
    <input type="submit"  style="padding: 5px 10px; margin-left:200px;" value="Reset" name="reset"/>
</form>
<script>
$(document).ready(function(){
setInterval(function(){
      $("#cal").load(window.location.href + " #cal" );
}, 5000);
});
</script>
</body>
</html>